# Generated by Django 4.2.11 on 2024-05-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='Category',
            field=models.CharField(choices=[('WA', 'WashingMachine'), ('FR', 'Refridgerator'), ('CR', 'Camera'), ('MB', 'mobile'), ('TB', 'Tabs'), ('HE', 'HomeElectoronics'), ('SQ', 'Security')], max_length=2),
        ),
    ]
