# Generated by Django 4.2.11 on 2024-05-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_oprice',
            new_name='discounted_price',
        ),
    ]
